import React from 'react';

// ─── Shared style tokens ────────────────────────────────────────────────────
const mainTitle = {
  fontSize: '1.15rem',
  fontWeight: 700,
  color: '#fff',
  lineHeight: 1.5,
  marginBottom: '16px',
  letterSpacing: '-0.01em',
};

const subHeadingStyle = {
  fontSize: '0.72rem',
  fontWeight: 700,
  color: 'var(--accent)',
  letterSpacing: '0.13em',
  textTransform: 'uppercase',
  marginTop: '0',
  marginBottom: '8px',
};

const bodyStyle = {
  fontSize: '0.97rem',
  color: 'var(--text-primary)',
  lineHeight: 1.75,
  marginBottom: '0',
};

const mutedStyle = {
  ...bodyStyle,
  color: 'var(--text-secondary)',
  fontSize: '0.9rem',
  marginTop: '8px',
};

const dividerStyle = {
  border: 'none',
  borderTop: '1px solid rgba(255,255,255,0.07)',
  margin: '18px 0 14px 0',
};

// ─── Sub-components ─────────────────────────────────────────────────────────
const Divider = () => <hr style={dividerStyle} />;

const SH = ({ children }) => <p style={subHeadingStyle}>{children}</p>;

const Body = ({ children, style }) => (
  <p style={{ ...bodyStyle, ...style }}>{children}</p>
);

const Muted = ({ children }) => <p style={mutedStyle}>{children}</p>;

const Bullet = ({ children }) => (
  <div style={{
    display: 'flex', alignItems: 'flex-start', gap: '10px',
    fontSize: '0.95rem', color: 'var(--text-primary)',
    lineHeight: 1.65, marginBottom: '2px',
  }}>
    <span style={{ color: 'var(--accent)', flexShrink: 0, marginTop: '4px', fontSize: '0.7rem' }}>▸</span>
    <span>{children}</span>
  </div>
);

const Block = ({ children }) => (
  <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
    {children}
  </div>
);

// ─── SECTION 1 — Context & Classification™ ──────────────────────────────────
export function ContextInfoContent() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <h3 style={mainTitle}>
        Understanding Who You Are, Where You Operate, and the Future Environment You Are Navigating
      </h3>

      <Body>
        Thank you for participating in the{' '}
        <strong>Invictus Future Readiness Diagnostic™ (IFRD™)</strong>.
      </Body>

      <Body>
        This section forms part of the{' '}
        <strong>Invictus Global Future Readiness Index™ (IGFRI™)</strong>, an ongoing initiative
        designed to understand how leaders, organisations, industries and nations are preparing for
        future uncertainty, disruption, opportunity and transformation.
      </Body>

      <Divider />

      <SH>The information collected in this section enables:</SH>
      <Block>
        <Bullet>Future Readiness Benchmarking</Bullet>
        <Bullet>Industry Comparisons</Bullet>
        <Bullet>Country and Regional Comparisons</Bullet>
        <Bullet>Leadership Readiness Analysis</Bullet>
        <Bullet>AI Readiness Analysis</Bullet>
        <Bullet>Workforce Readiness Analysis</Bullet>
        <Bullet>Strategic Intelligence Analysis</Bullet>
        <Bullet>Emerging Risk Analysis</Bullet>
        <Bullet>Longitudinal Future Readiness Tracking</Bullet>
      </Block>

      <Divider />

      <Body>
        The quality of the intelligence generated by IGFRI™ depends on understanding the context
        in which leaders and organisations operate.
      </Body>

      <Muted>
        All information will be treated with strict confidentiality and reported only in
        aggregated and anonymised form unless otherwise agreed.
      </Muted>

      <div style={{
        display: 'inline-flex', alignItems: 'center', gap: '8px',
        background: 'rgba(0,230,118,0.08)', border: '1px solid rgba(0,230,118,0.25)',
        borderRadius: '20px', padding: '6px 16px', fontSize: '0.88rem',
        color: 'var(--accent)', fontWeight: 600, marginTop: '6px', alignSelf: 'flex-start',
      }}>
        ⏱&nbsp; Estimated Completion Time: 15 – 20 Minutes
      </div>
    </div>
  );
}

// ─── SECTION 1 — Declaration ─────────────────────────────────────────────────
export function DeclarationInfoContent() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
      <Body>
        Before proceeding with the{' '}
        <strong>Invictus Future Readiness Diagnostic™ (IFRD™)</strong>, please read the
        following information carefully.
      </Body>

      <Divider />

      <SH>Why Your Participation Matters</SH>
      <Body>
        Most organisations measure performance.{' '}
        <strong>Very few measure preparedness.</strong>
      </Body>
      <Body>
        By participating in the IFRD™, you are contributing to a growing body of knowledge designed
        to help leaders, organisations, industries and societies better understand preparedness for
        future uncertainty, disruption and opportunity.
      </Body>
      <Body>
        The collective intelligence generated through the IFRD™ ecosystem supports the development
        of future benchmarks, research and the{' '}
        <strong>Invictus Global Future Readiness Index™ (IGFRI™)</strong>. Together, these insights
        help organisations move beyond measuring performance and towards understanding preparedness.
      </Body>

      <Divider />

      <SH>Purpose of Information Collection</SH>
      <Body>
        The information collected through the IFRD™ is used exclusively for purposes related to the
        IFRD™ ecosystem and the advancement of Future Preparedness Intelligence™. This information enables:
      </Body>
      <Block>
        <Bullet>Generation of individual, team and organisational reports.</Bullet>
        <Bullet>Benchmarking and comparative analysis.</Bullet>
        <Bullet>Strategic foresight and preparedness research.</Bullet>
        <Bullet>Continuous improvement of the IFRD™ platform.</Bullet>
        <Bullet>Development of the Corporate Future Readiness Benchmark™.</Bullet>
        <Bullet>Development of the Invictus Global Future Readiness Index™ (IGFRI™).</Bullet>
        <Bullet>Industry, regional and global preparedness insights.</Bullet>
        <Bullet>Development of future analytics and intelligence capabilities.</Bullet>
      </Block>
      <Muted>
        Information collected through the IFRD™ will not be sold or used for purposes unrelated
        to the IFRD™ ecosystem.
      </Muted>

      <Divider />

      <SH>Confidentiality</SH>
      <Body>
        All information provided will be treated with strict confidentiality. Individual responses
        will not be disclosed to third parties without prior consent unless required by applicable
        laws and regulations.
      </Body>
      <Body>
        Assessment findings, benchmarking outputs, research reports and publications may be presented
        only in aggregated and anonymised form. No individual, team or organisation will be identified
        without explicit permission.
      </Body>

      <Divider />

      <SH>Benchmarking, Research and Publications</SH>
      <Body>
        Participants acknowledge and understand that anonymised and aggregated information may be used for:
      </Body>
      <Block>
        <Bullet>Benchmarking and comparative studies.</Bullet>
        <Bullet>Industry and sector analysis.</Bullet>
        <Bullet>Country and regional comparisons.</Bullet>
        <Bullet>Academic and professional research.</Bullet>
        <Bullet>Publications and future reports.</Bullet>
        <Bullet>Development of future preparedness indices.</Bullet>
        <Bullet>Development of AI-powered analytics and intelligence capabilities.</Bullet>
        <Bullet>Continuous improvement of the IFRD™ ecosystem.</Bullet>
      </Block>
      <Muted>No individual, team or organisation will be identified without prior written permission.</Muted>

      <Divider />

      <SH>Data Retention</SH>
      <Body>Information collected through the IFRD™ may be retained for purposes related to:</Body>
      <Block>
        <Bullet>Assessment reporting.</Bullet>
        <Bullet>Benchmarking.</Bullet>
        <Bullet>Longitudinal studies.</Bullet>
        <Bullet>Research and publications.</Bullet>
        <Bullet>Continuous improvement of the IFRD™ ecosystem.</Bullet>
        <Bullet>Development of future preparedness intelligence capabilities.</Bullet>
      </Block>
      <Muted>
        Information will be managed responsibly and in accordance with applicable laws,
        regulations and good data governance practices.
      </Muted>

      <Divider />

      <SH>Commitment to Responsible Data Management</SH>
      <Body>
        Invictus Leader is committed to protecting personal information and managing assessment data
        responsibly. Information collected through the IFRD™ will be handled in accordance with
        applicable privacy and data protection laws and regulations.
      </Body>

      <Divider />

      <SH>Voluntary Participation</SH>
      <Body>
        Participation in the IFRD™ is voluntary. Participants may discontinue the assessment at any
        time. Where appropriate, participants may choose not to answer selected questions.
      </Body>

      <Divider />

      <SH>Accuracy of Responses</SH>
      <Body>
        The quality and usefulness of the assessment depend upon the accuracy and honesty of the
        information provided. Participants are encouraged to answer based on the{' '}
        <strong>current reality</strong> of their organisation rather than aspirations or desired
        future states.
      </Body>

      <Divider />

      <SH>Intended Use of Results</SH>
      <Body>The IFRD™ is intended to support:</Body>
      <Block>
        <Bullet>Learning and development.</Bullet>
        <Bullet>Leadership conversations.</Bullet>
        <Bullet>Strategic thinking.</Bullet>
        <Bullet>Benchmarking and comparative analysis.</Bullet>
        <Bullet>Organisational preparedness.</Bullet>
        <Bullet>Strategic foresight and decision-making.</Bullet>
        <Bullet>Future preparedness improvement.</Bullet>
      </Block>
      <Muted>
        The results are intended for developmental and intelligence purposes only. They should not
        be interpreted as a guarantee, prediction or assurance of future organisational performance
        or outcomes.
      </Muted>

      <Divider />

      <SH>Use of Advanced Analytics</SH>
      <Body>
        Invictus Leader may use advanced analytics and AI-enabled capabilities to improve the quality,
        benchmarking and intelligence capabilities of the IFRD™ platform. Such use will not identify
        individuals, teams or organisations without explicit permission.
      </Body>

      <Divider />

      <SH>Intellectual Property</SH>
      <Body>
        The Invictus Future Readiness Diagnostic™ (IFRD™), its methodologies, frameworks, models,
        scoring systems and associated intellectual property remain the property of Invictus Leader.
        Participation in the assessment does not transfer ownership of any intellectual property rights.
      </Body>

      <Divider />

      <SH>Limitation of Responsibility</SH>
      <Body>
        The results and insights generated by the IFRD™ are intended to support learning, reflection,
        benchmarking and strategic conversations. They should not be interpreted as financial, legal,
        investment, psychological or professional advice. Invictus Leader shall not be responsible for
        decisions, actions or outcomes arising solely from the use of assessment findings.
      </Body>

      <Divider />

      <SH>Continuous Improvement</SH>
      <Body>
        The IFRD™ platform, methodologies and benchmarking models may evolve over time as new research,
        insights and capabilities emerge. Invictus Leader reserves the right to enhance and improve
        the platform in support of better Future Preparedness Intelligence™.
      </Body>

      <Divider />

      <SH>Important Notice</SH>
      <Body>
        By participating in the IFRD™, participants acknowledge and agree that anonymised and aggregated
        information may be used for benchmarking, research, publications and the continued development
        of the IFRD™ ecosystem, including:
      </Body>
      <Block>
        <Bullet>The Corporate Future Readiness Benchmark™;</Bullet>
        <Bullet>Industry and sector benchmarks;</Bullet>
        <Bullet>Country and regional benchmarks;</Bullet>
        <Bullet>Future preparedness research;</Bullet>
        <Bullet>AI-powered intelligence capabilities.</Bullet>
      </Block>
      <Muted>No individual, team or organisation will be identified without explicit permission.</Muted>
    </div>
  );
}
